// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pawsy.Infrastructure.Data;

#nullable disable

namespace Pawsy.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024210239_feedPetAndCategoryTable")]
    partial class feedPetAndCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pawsy.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mascotas caninas",
                            Name = "Perros"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mascotas felinas",
                            Name = "Gatos"
                        });
                });

            modelBuilder.Entity("Pawsy.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            CategoryId = 1,
                            Description = "Fusce tincidunt maximus leo, sed scelerisque massa auctor sit amet.",
                            Gender = "Macho",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Pupo"
                        },
                        new
                        {
                            Id = 2,
                            Age = 5,
                            CategoryId = 1,
                            Description = "Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            Gender = "Macho",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Pipo"
                        },
                        new
                        {
                            Id = 3,
                            Age = 7,
                            CategoryId = 2,
                            Description = "Fusce tincidunt maximus leo, sed scelerisque massa auctor sit amet.",
                            Gender = "Macho",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Tito"
                        });
                });

            modelBuilder.Entity("Pawsy.Domain.Entities.Pet", b =>
                {
                    b.HasOne("Pawsy.Domain.Entities.Category", "Category")
                        .WithMany("Pets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pawsy.Domain.Entities.Category", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
